name: Test Coverage
on:
  pull_request:
  push:
    branches:
      - master
      - release/**
  
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    needs: split-test-files
    steps:
      - uses: actions/checkout@v2
      - name: test & coverage report creation
        run: |
           go test ./... -mod=readonly -timeout 8m -race -coverprofile=coverage.txt -covermode=atomic
        if: env.GIT_DIFF
      - uses: codecov/codecov-action@v1.0.13
